# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Bridge City Paddling Club
email: jeremy@bridgecitypaddling.org
description: > # this means to ignore newlines until "baseurl:"
  Bridge City is a competitive Dragon Boat and Outrigger Canoe Club in Portland, Oregon. We are a 501(c)3, non-profit organization.
baseurl: "/" # the subpath of your site, e.g. /blog
url: "http://www.bridgecitypaddling.org/" # the base hostname & protocol for your site
twitter_username: maple_and_pine
github_username:  mapleandpine

# Build settings
markdown: kramdown
